/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c  (STM32F401RE – Consensus Node "F401")
  * @brief          : Distributed irrigation consensus protocol
  *
  * Topology
  * --------
  *   F401 USART1 TX  ──►  F303 USART1 RX   (STATE packets)
  *   F401 USART1 RX  ◄──  F303 USART1 TX   (STATE packets back)
  *   F401 USART2     ──►  ST-LINK / debug terminal
  *
  * Packet formats (newline-terminated ASCII)
  * ------------------------------------------
  *   STATE|NODE=F401|SM=<soil>|T=<temp>|NW=<0/1>|SEQ=<n>|TS=<ms>
  *   CONSENSUS|ACT=<IRRIGATE/WAIT/SLEEP>|REASON=<text>|BY=F401|SEQ=<n>|TS=<ms>
  *
  * Consensus rules (same on both boards)
  * --------------------------------------
  *   both NW=1  →  IRRIGATE  (actuate immediately)
  *   one  NW=1  →  WAIT      (recheck after 30 min window)
  *   none NW=1  →  SLEEP     (check again after 2 h window)
  *   peer stale →  FALLBACK  (local-safe: WAIT if local NW, else SLEEP)
  *
  * Pin assignments
  * ---------------
  *   DHT11   : PA8  (defined in dht11.h)
  *   Soil 1  : ADC1 – PB0 / A3  (channel 8)
  *   Soil 2  : ADC1 – PC1 / A4  (channel 11)
  *   Pump    : PB5  (active HIGH)
  *
  ******************************************************************************
  */
/* USER CODE END Header */

#include "main.h"
#include "dht11.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

/* =========================================================================
 * Compile-time identity
 * ========================================================================= */
#define NODE_ID            "F401"
#define PEER_ID            "F303"

/* =========================================================================
 * Consensus thresholds (must match F303 values exactly)
 * ========================================================================= */
#define SOIL_WET_THRESHOLD     2000U   /* ADC counts: < threshold => dry => needs water */
#define PEER_STALE_MS       600000UL   /* 10 min: peer data considered stale            */
#define BROADCAST_PERIOD_MS  15000UL   /* 15 s between STATE broadcasts                 */
#define WAIT_WINDOW_MS     1800000UL   /* 30 min: ONE_NEEDS re-evaluation window         */
#define SLEEP_WINDOW_MS    7200000UL   /* 2 h:   NONE_NEED  re-evaluation window         */
#define RX_TIMEOUT_MS         100UL   /* UART receive poll timeout                      */
#define RX_BUF_LEN             192U   /* receive line buffer                            */

/* =========================================================================
 * HAL handles (generated by CubeMX – keep as-is)
 * ========================================================================= */
ADC_HandleTypeDef hadc1;
UART_HandleTypeDef huart1;   /* peer link (F303)           */
UART_HandleTypeDef huart2;   /* debug / cloud terminal     */

/* =========================================================================
 * Consensus types
 * ========================================================================= */
typedef enum {
    ACT_IRRIGATE = 0,
    ACT_WAIT,
    ACT_SLEEP
} ConsensusAction_t;

typedef struct {
    char     nodeId[8];
    uint16_t soil;         /* raw ADC value (average of two sensors)  */
    int16_t  tempC;
    uint8_t  needsWater;   /* 1 = dry, 0 = wet                        */
    uint32_t seq;
    uint32_t ts;           /* HAL_GetTick() at the time of reading     */
    uint8_t  valid;        /* 0 = no data yet                          */
} NodeState_t;

/* =========================================================================
 * Global state
 * ========================================================================= */
static NodeState_t     g_local;
static NodeState_t     g_peer;
static ConsensusAction_t g_action      = ACT_WAIT;
static uint32_t        g_actionSinceMs = 0;
static uint32_t        g_lastBcastMs   = 0;
static uint32_t        g_localSeq      = 0;

/* UART line-receive buffer */
static char    g_rxBuf[RX_BUF_LEN];
static uint16_t g_rxIdx = 0;

/* =========================================================================
 * Private function prototypes
 * ========================================================================= */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_ADC1_Init(void);

static uint16_t Read_ADC_Channel(uint32_t channel);

static void     Consensus_ReadSensors(void);
static void     Consensus_Broadcast(void);
static uint8_t  Consensus_TryReceiveLine(char *lineBuf, uint16_t maxLen);
static uint8_t  Consensus_ParsePeerState(const char *line, NodeState_t *out);
static ConsensusAction_t Consensus_Evaluate(const char **reasonOut);
static void     Consensus_Apply(ConsensusAction_t act, const char *reason);
static void     Consensus_PublishDecision(ConsensusAction_t act, const char *reason);
static void     Consensus_SetPump(uint8_t on);
static void     DBG(const char *msg);

/* =========================================================================
 * Helpers
 * ========================================================================= */

static void DBG(const char *msg)
{
    HAL_UART_Transmit(&huart2, (uint8_t *)msg, (uint16_t)strlen(msg), 200);
}

static uint16_t Read_ADC_Channel(uint32_t channel)
{
    ADC_ChannelConfTypeDef sConfig = {0};
    sConfig.Channel      = channel;
    sConfig.Rank         = 1;
    sConfig.SamplingTime = ADC_SAMPLETIME_3CYCLES;
    if (HAL_ADC_ConfigChannel(&hadc1, &sConfig) != HAL_OK) return 0u;

    HAL_ADC_Start(&hadc1);
    HAL_ADC_PollForConversion(&hadc1, HAL_MAX_DELAY);
    uint16_t v = (uint16_t)HAL_ADC_GetValue(&hadc1);
    HAL_ADC_Stop(&hadc1);
    return v;
}

static void Consensus_SetPump(uint8_t on)
{
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, on ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/* =========================================================================
 * Sensor sampling
 * ========================================================================= */
static void Consensus_ReadSensors(void)
{
    uint16_t s1 = Read_ADC_Channel(ADC_CHANNEL_8);    /* PB0 / A3 */
    uint16_t s2 = Read_ADC_Channel(ADC_CHANNEL_11);   /* PC1 / A4 */
    uint16_t soilAvg = (uint16_t)((s1 + s2) / 2u);

    DHT11_Data_t dht = {0};
    int16_t tempC = 0;
    if (DHT11_ReadData(&dht) == HAL_OK) {
        tempC = (int16_t)dht.Temperature;
    }

    strncpy(g_local.nodeId, NODE_ID, sizeof(g_local.nodeId) - 1);
    g_local.soil       = soilAvg;
    g_local.tempC      = tempC;
    g_local.needsWater = (soilAvg < SOIL_WET_THRESHOLD) ? 1u : 0u;
    g_local.seq        = ++g_localSeq;
    g_local.ts         = HAL_GetTick();
    g_local.valid      = 1u;
}

/* =========================================================================
 * Broadcast local STATE packet to peer + debug terminal
 * ========================================================================= */
static void Consensus_Broadcast(void)
{
    char buf[160];
    snprintf(buf, sizeof(buf),
             "STATE|NODE=%s|SM=%u|T=%d|NW=%u|SEQ=%lu|TS=%lu\r\n",
             g_local.nodeId,
             (unsigned)g_local.soil,
             (int)g_local.tempC,
             (unsigned)g_local.needsWater,
             (unsigned long)g_local.seq,
             (unsigned long)g_local.ts);

    HAL_UART_Transmit(&huart1, (uint8_t *)buf, (uint16_t)strlen(buf), 300);
    DBG(buf);
}

/* =========================================================================
 * Non-blocking line receive from UART1 (peer link)
 * Returns 1 when a complete line is available in lineBuf.
 * ========================================================================= */
static uint8_t Consensus_TryReceiveLine(char *lineBuf, uint16_t maxLen)
{
    uint8_t rx = 0;
    while (HAL_UART_Receive(&huart1, &rx, 1, RX_TIMEOUT_MS) == HAL_OK)
    {
        if (rx == '\r') continue;
        if (rx == '\n') {
            g_rxBuf[g_rxIdx] = '\0';
            if (g_rxIdx > 0) {
                strncpy(lineBuf, g_rxBuf, maxLen - 1);
                lineBuf[maxLen - 1] = '\0';
                g_rxIdx = 0;
                return 1u;
            }
            g_rxIdx = 0;
            continue;
        }
        if (g_rxIdx < (RX_BUF_LEN - 1)) {
            g_rxBuf[g_rxIdx++] = (char)rx;
        } else {
            g_rxIdx = 0; /* overflow – discard */
        }
    }
    return 0u;
}

/* =========================================================================
 * Parse STATE packet from peer
 * Format: STATE|NODE=X|SM=Y|T=Z|NW=W|SEQ=S|TS=T
 * ========================================================================= */
static uint8_t Consensus_ParsePeerState(const char *line, NodeState_t *out)
{
    if (strncmp(line, "STATE|", 6) != 0) return 0u;

    /* Accept only packets from the known peer */
    if (strstr(line, "NODE=" PEER_ID) == NULL) return 0u;

    const char *p;

    p = strstr(line, "|SM=");
    if (!p) return 0u;
    out->soil = (uint16_t)atoi(p + 4);

    p = strstr(line, "|T=");
    if (!p) return 0u;
    out->tempC = (int16_t)atoi(p + 3);

    p = strstr(line, "|NW=");
    if (!p) return 0u;
    out->needsWater = (uint8_t)atoi(p + 4);

    p = strstr(line, "|SEQ=");
    if (!p) return 0u;
    out->seq = (uint32_t)atol(p + 5);

    /* TS – use LOCAL receive time, not sender's clock.
     * Sender's HAL_GetTick() is on a different epoch; comparing it to
     * our own HAL_GetTick() would cause uint32 wrap and the peer would
     * always appear stale.                                            */
    out->ts = HAL_GetTick();

    strncpy(out->nodeId, PEER_ID, sizeof(out->nodeId) - 1);
    out->valid = 1u;
    return 1u;
}

/* =========================================================================
 * Core consensus decision engine (identical to F303)
 * ========================================================================= */
static ConsensusAction_t Consensus_Evaluate(const char **reasonOut)
{
    uint32_t now      = HAL_GetTick();
    uint8_t  peerFresh = (g_peer.valid &&
                          (now - g_peer.ts) <= PEER_STALE_MS) ? 1u : 0u;

    if (!peerFresh) {
        *reasonOut = "PEER_STALE_FALLBACK";
        return g_local.needsWater ? ACT_WAIT : ACT_SLEEP;
    }

    if (g_local.needsWater && g_peer.needsWater) {
        *reasonOut = "BOTH_NEED";
        return ACT_IRRIGATE;
    }
    if (g_local.needsWater || g_peer.needsWater) {
        *reasonOut = "ONE_NEEDS";
        return ACT_WAIT;
    }
    *reasonOut = "NONE_NEED";
    return ACT_SLEEP;
}

/* =========================================================================
 * Publish CONSENSUS decision
 * ========================================================================= */
static void Consensus_PublishDecision(ConsensusAction_t act, const char *reason)
{
    const char *actStr = (act == ACT_IRRIGATE) ? "IRRIGATE" :
                         (act == ACT_SLEEP)    ? "SLEEP"    : "WAIT";
    char buf[192];
    snprintf(buf, sizeof(buf),
             "CONSENSUS|ACT=%s|REASON=%s|BY=%s|SEQ=%lu|TS=%lu\r\n",
             actStr, reason, NODE_ID,
             (unsigned long)g_localSeq,
             (unsigned long)HAL_GetTick());

    /* Wait 100ms before sending to NodeMCU.
     * Since STATE and CONSENSUS are generated back-to-back,
     * this prevents the NodeMCU's SoftwareSerial buffer from overflowing. */
    HAL_Delay(100);
    HAL_UART_Transmit(&huart1, (uint8_t *)buf, (uint16_t)strlen(buf), 300);
    DBG(buf);   /* huart2 → debug terminal */
}

/* =========================================================================
 * Apply action: drive pump + publish packet + update state
 * ========================================================================= */
static void Consensus_Apply(ConsensusAction_t act, const char *reason)
{
    if (act != g_action) {
        g_actionSinceMs = HAL_GetTick();
    }
    g_action = act;

    Consensus_SetPump(act == ACT_IRRIGATE ? 1u : 0u);
    Consensus_PublishDecision(act, reason);
}

/* =========================================================================
 * Main loop
 * ========================================================================= */
int main(void)
{
    HAL_Init();
    SystemClock_Config();

    MX_GPIO_Init();
    MX_USART1_UART_Init();
    MX_USART2_UART_Init();
    MX_ADC1_Init();

    DHT11_Init();
    HAL_Delay(2000);

    g_actionSinceMs = HAL_GetTick();
    g_lastBcastMs   = HAL_GetTick() - BROADCAST_PERIOD_MS; /* fire first cycle immediately */

    DBG("[F401] Consensus node started\r\n");

    char lineBuf[RX_BUF_LEN];

    while (1)
    {
        /* ── 1. Drain incoming UART bytes, parse any complete STATE line ── */
        if (Consensus_TryReceiveLine(lineBuf, sizeof(lineBuf))) {
            NodeState_t incoming = {0};
            if (Consensus_ParsePeerState(lineBuf, &incoming)) {
                g_peer = incoming;
                DBG("[PEER] ");
                DBG(lineBuf);
                DBG("\r\n");

                /* Forward the peer (F303) packet to NodeMCU so it reaches the cloud */
                char fwd[128];
                snprintf(fwd, sizeof(fwd), "%s\r\n", lineBuf);
                HAL_UART_Transmit(&huart1, (uint8_t *)fwd, (uint16_t)strlen(fwd), 100);
            }
        }

        /* ── 2. Every BROADCAST_PERIOD_MS: read sensors + decide ── */
        if ((HAL_GetTick() - g_lastBcastMs) >= BROADCAST_PERIOD_MS)
        {
            g_lastBcastMs = HAL_GetTick();

            Consensus_ReadSensors();
            Consensus_Broadcast();

            const char *reason = "UNKNOWN";
            ConsensusAction_t next = Consensus_Evaluate(&reason);

            if (next == ACT_IRRIGATE) {
                /* IRRIGATE – no window, actuate immediately */
                Consensus_Apply(next, reason);

            } else if (next == ACT_WAIT) {
                /* Time-gate only applies to genuine ONE_NEEDS;
                 * pass PEER_STALE_FALLBACK and others straight through. */
                if (strcmp(reason, "ONE_NEEDS") == 0) {
                    uint8_t windowElapsed = ((HAL_GetTick() - g_actionSinceMs) >= WAIT_WINDOW_MS);
                    Consensus_Apply(ACT_WAIT,
                                    windowElapsed ? reason : "ONE_NEEDS_WAITING_WINDOW");
                } else {
                    Consensus_Apply(next, reason);
                }

            } else { /* ACT_SLEEP */
                if (strcmp(reason, "NONE_NEED") == 0) {
                    uint8_t windowElapsed = ((HAL_GetTick() - g_actionSinceMs) >= SLEEP_WINDOW_MS);
                    Consensus_Apply(ACT_SLEEP,
                                    windowElapsed ? reason : "NONE_NEED_SLEEP_WINDOW");
                } else {
                    Consensus_Apply(next, reason);
                }
            }
        }
    }
}

/* =========================================================================
 * HAL peripheral initialisation (CubeMX-generated, untouched)
 * ========================================================================= */

void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    __HAL_RCC_PWR_CLK_ENABLE();
    __HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE2);

    RCC_OscInitStruct.OscillatorType      = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState            = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState        = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource       = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM            = 16;
    RCC_OscInitStruct.PLL.PLLN            = 336;
    RCC_OscInitStruct.PLL.PLLP            = RCC_PLLP_DIV4;
    RCC_OscInitStruct.PLL.PLLQ            = 7;
    if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) { Error_Handler(); }

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
                                     | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV2;
    RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;
    if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK) { Error_Handler(); }
}

static void MX_ADC1_Init(void)
{
    /* NbrOfConversion=1 because we call ConfigChannel before each read */
    hadc1.Instance                   = ADC1;
    hadc1.Init.ClockPrescaler        = ADC_CLOCK_SYNC_PCLK_DIV4;
    hadc1.Init.Resolution            = ADC_RESOLUTION_12B;
    hadc1.Init.ScanConvMode          = DISABLE;
    hadc1.Init.ContinuousConvMode    = DISABLE;
    hadc1.Init.DiscontinuousConvMode = DISABLE;
    hadc1.Init.ExternalTrigConvEdge  = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc1.Init.ExternalTrigConv      = ADC_SOFTWARE_START;
    hadc1.Init.DataAlign             = ADC_DATAALIGN_RIGHT;
    hadc1.Init.NbrOfConversion       = 1;
    hadc1.Init.DMAContinuousRequests = DISABLE;
    hadc1.Init.EOCSelection          = ADC_EOC_SINGLE_CONV;
    if (HAL_ADC_Init(&hadc1) != HAL_OK) { Error_Handler(); }
}

static void MX_USART1_UART_Init(void)
{
    huart1.Instance          = USART1;
    huart1.Init.BaudRate     = 115200;
    huart1.Init.WordLength   = UART_WORDLENGTH_8B;
    huart1.Init.StopBits     = UART_STOPBITS_1;
    huart1.Init.Parity       = UART_PARITY_NONE;
    huart1.Init.Mode         = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart1) != HAL_OK) { Error_Handler(); }
}

static void MX_USART2_UART_Init(void)
{
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart2) != HAL_OK) { Error_Handler(); }
}

static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    __HAL_RCC_GPIOC_CLK_ENABLE();
    __HAL_RCC_GPIOH_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();

    /* Pump / LED on PB5 – start OFF */
    HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_RESET);
    GPIO_InitStruct.Pin   = GPIO_PIN_5;
    GPIO_InitStruct.Mode  = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull  = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

    /* User button B1 – PC13 */
    GPIO_InitStruct.Pin  = B1_Pin;
    GPIO_InitStruct.Mode = GPIO_MODE_IT_FALLING;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(B1_GPIO_Port, &GPIO_InitStruct);
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}

#ifdef USE_FULL_ASSERT
void assert_failed(uint8_t *file, uint32_t line)
{
    (void)file; (void)line;
}
#endif /* USE_FULL_ASSERT */
